name: Build

on:
  push:
    branches:
      - develop
      - master
      - beta
      - stable
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  MICROCHIP_DOWNLOAD_LOCATION: https://thethingsproducts.blob.core.windows.net/the-things-gateway/ci

  BUCKET_NAME: "gateway-test-kickstartergateways3bucket-1lcb7704s8js"
  AWS_REGION: "us-east-1"
  AWS_ROLE: "arn:aws:iam::368443094578:role/GitHubActions_TheThingsProducts-gateway"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        uses: ./.github/build-action
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            firmware/firmware.hex
            firmware/firmware-with-bootloader.hex
            firmware/checksums
            firmware/disassembly.txt
      - name: Extract the name
        id: extract_name
        run: echo ::set-output name=NAME::${GITHUB_REF#refs/*/}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "${{ env.AWS_REGION }}"
          role-to-assume: "${{ env.AWS_ROLE }}"
          role-session-name: GitHubActions_TheThingsProduct-gateway-build
      - name: Upload to AWS S3
        run: |
          ls ./firmware
          for file in ${FILES}; do
            aws s3 cp "./firmware/${file}" "${BUCKET}/${file}"
          done
        env:
          FILES: "firmware.hex firmware-with-bootloader.hex checksums disassembly.txt"
          BUCKET: "s3://${{ env.BUCKET_NAME }}/v1/${{ steps.extract_name.outputs.NAME }}"
